### ISSUE TITLE
The project is active?

### ISSUE THREAD

**Issue by kaoecoito** [braylabs/m4j#2]
Hello Brian,

I work in a Brazilian software company that develops ERP in MUMPS.
It is a very large system, a year that was converted from the MUMPS Intersystems for GTM. Also recreated some implementations connectors and Java tools to maintain compatibility with Intersystems.
Currently the company is in a process of changing everything to java and I enjoyed your M4J project.
The project is active?

Thank you

**Comment by bbray** [comment]
Hi, 
Unfortunately it is not active, it was just a hobby of mine a couple years ago when I was working with MUMPS systems. I hope that someday I can pick it back up!

Brian
