### ISSUE TITLE
Build failure with Maven for H2 global store

### ISSUE THREAD

**Issue by strojacek** [braylabs/m4j#6]
Hello,
I am currently trying to compile the system using Maven. After commenting out the references to the Cache dependency, and removing that dependency within the pom.xml file, I am getting this error related to the H2 global store:
```sh
[ERROR] /home/seth/Desktop/m4j/src/main/java/com/braylabs/m4j/global/GlobalStore.java:[51,49] cannot find symbol
  symbol:   method removeMap()
  location: class org.h2.mvstore.MVMap<java.lang.Object,java.lang.Object>
[ERROR] /home/seth/Desktop/m4j/src/main/java/com/braylabs/m4j/global/MMap.java:[286,39] wrong number of type arguments; required 2
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.197 s
[INFO] Finished at: 2022-04-24T20:08:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project m4j: Compilation failure: Compilation failure: 
[ERROR] /home/seth/Desktop/m4j/src/main/java/com/braylabs/m4j/global/GlobalStore.java:[51,49] cannot find symbol
[ERROR]   symbol:   method removeMap()
[ERROR]   location: class org.h2.mvstore.MVMap<java.lang.Object,java.lang.Object>
[ERROR] /home/seth/Desktop/m4j/src/main/java/com/braylabs/m4j/global/MMap.java:[286,39] wrong number of type arguments; required 2

```
Would there be a specific value that I would need to set for the 2nd argument?
Thank you!
-Seth

**Comment by bbray** [comment]
@strojacek I have not kept up to date with this project or the H2 MVStore.  I did do a couple of the dependabot suggested upgrades to H2Database this year which probably caused this issue.  I would suggest reverting to the original H2Database dependency in this commit https://github.com/braylabs/m4j/commit/13a99301b79477e93abfedc5b19bfd869d6ae2d7 (1.3.x) as the 2.x branch probably had some API changes and the security issue was very minor IIRC.

**Comment by strojacek** [comment]
Thank you, your suggestion fixed the error!
-Seth
